openapi: 3.0.3
info:
  title: API Transactions ArgentBank (Local)
  version: 1.0.0
  description: API RESTful pour gérer les transactions bancaires d’un utilisateur sur un environnement local
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3001/api
    description: Serveur local backend

tags:
  - name: Accounts
    description: Gestion des comptes et des transactions par compte
  - name: Transactions
    description: Détails et modification d’une transaction

components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    Transaction:
      type: object
      required:
        - id
        - date
        - description
        - amount
        - balance
        - type
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        description:
          type: string
        amount:
          type: number
          format: float
        balance:
          type: number
          format: float
        type:
          type: string
        category:
          type: string
        notes:
          type: string

security:
  - tokenAuth: []

paths:
  /accounts:
    get:
      operationId: getAllAccounts
      summary: Récupère tous les comptes bancaires
      security:
        - tokenAuth: []
      tags:
        - Accounts
      responses:
        '200':
          description: Liste des comptes bancaires
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401' :
          description: Utilisateur non authentifié
        '500':
          description: Erreur interne du serveur
  /transactions/{accountId}:
    get:
      operationId: getTransactionsByAccount
      summary: Récupère toutes les transactions
      security:
        - tokenAuth: []
      tags:
        - Transactions
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: ID du compte bancaire
      responses:
        '200':
          description: Liste des transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400' :
          description: Requête invalide
        '401' :
          description: Utilisateur non authentifié
        '404':
          description: Aucune transaction trouvée pour cet ID de compte
        '500':
          description: Erreur interne du serveur

  /transactions:
    get:
      operationId: getCurrentMonthTransactions
      summary: Récupère les transactions du mois en cours
      security:
        - tokenAuth: []
      tags:
        - Transactions
      responses:
        '200':
          description: Liste des transactions du mois en cours
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400' :
          description: Requête invalide'
        '401' :
          description: Utilisateur non authentifié
        '404':
          description: Aucune transaction trouvée pour le mois en cours
        '500':
          description: Erreur interne du serveur
  /transactions/transaction/{idTransaction}:
    get:
      operationId: getTransactionById
      summary: Obtenir les détails d’une transaction
      security:
        - tokenAuth: []
      tags:
        - Transactions
      parameters:
        - in: path
          name: idTransaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails d’une transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400' :
          description: Transaction non trouvée
        '401' :
          description: Utilisateur non authentifié
        '404' :
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
          
    patch:
      operationId: updateTransaction
      summary: Modifier la catégorie et/ou la note d'une transaction
      security:
        - tokenAuth: []
      tags:
        - Transactions
      parameters:
        - in: path
          name: idTransaction
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                notes:
                  type: string
              additionalProperties: false
      responses:
        '200':
          description: Catégorie mise à jour avec succès
        '400' :
          description: Donnée de catégorie manquante ou invalide
        '401' :
          description: Utilisateur non authentifié
        '404' :
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

    post:
      operationId: addTransaction
      summary: Ajouter une nouvelle transaction
      security:
        - tokenAuth: []
      tags:
        - Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - date
                - description
                - amount
                - balance
                - type
              properties:
                date:
                  type: string
                  format: date
                description:
                  type: string
                amount:
                  type: number
                  format: float
                balance:
                  type: number
                  format: float
                type:
                  type: string
                category:
                  type: string
                notes:
                  type: string
              additionalProperties: false
      responses:
        '201':
          description: Transaction créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Données invalides
        '401':
          description: Utilisateur non authentifié
        '500':
          description: Erreur interne du serveur

  /transactions/transaction/{idTransaction}:
    delete:
      operationId: deleteTransaction
      summary: Supprimer une transaction
      security:
        - tokenAuth: []
      tags:
        - Transactions
      parameters:
        - in: path
          name: idTransaction
          required: true
          schema:
            type: string
          description: ID de la transaction à supprimer
      responses:
        '204':
          description: Transaction supprimée avec succès
        '400':
          description: ID de transaction invalide
        '401':
          description: Utilisateur non authentifié
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
